Animation for locked driver door
Open-GTO/sa-mp-fixes pull request #64
Opened 2017-08-18 03:11 UTC by rt-2

I figured nobody had time to do this.
As I was watching the code, I felt like it was almost done just because I was looking at it, felt easy.
I though that copying the script would be easy, but I had to understand it completely to document it, well now it's done.
Side note: line 1220 was missing the _2

2017-08-18 17:47 UTC, ziggi requested changes
Thanks, but some improvements are required.

2017-08-18 17:47 UTC, ziggi commented on fixes.inc
> +	stock FIXES_GetVehicleParamsEx(vehicleid, engine, lights, alarm, doors, bonnet, boot, objective)
You forgot about ampersands.

2017-08-18 17:47 UTC, ziggi commented on fixes.inc
> +		return GetVehicleParamsEx(vehicleid, engine, lights, alarm, doors, bonnet, boot, objective);
I think what `return` should be replaced by variable and moved to the end of the function.
```Pawn
new
    ret = GetVehicleParamsEx(vehicleid, engine, lights, alarm, doors, bonnet, boot, objective);
//...
return ret;
```

2017-08-18 17:47 UTC, ziggi commented on fixes.inc
> +		#if !defined FILTERSCRIPT
This can be written in one line:
```pawn
#if FIX_OnPlayerEnterVehicle_3 && !FIXES_Single && !defined FILTERSCRIPT
```

2017-08-18 17:47 UTC, ziggi commented on fixes.inc
> +	static stock FIXES_StopPlayerEnterVehicle(playerid)
The function should be renamed to `_FIXES_StopPlayerEnterVehicle` ([guidelines](https://github.com/Open-GTO/sa-mp-fixes/blob/master/fixes.inc#L859-L861)).

2017-08-18 17:47 UTC, ziggi commented on fixes.inc
> +		player_data[playerid][e_IsOpening] = false;
Wrong variables.

2017-08-18 17:47 UTC, ziggi commented on fixes.inc
> +	bool:FIXES_gsPlayerVehEntering[MAX_PLAYERS],
We have `FIXES_gsPlayerBools` array for booleans.

2017-08-18 17:47 UTC, ziggi commented on fixes.inc
> +	FIXES_gsPlayerVehID[MAX_PLAYERS],
I think that `FIXES_gsPlayerVehicleID` name is better.

2017-08-18 17:47 UTC, ziggi commented on fixes.inc
> +	FIXES_gsPlayerVehTickCount[MAX_PLAYERS],
Same, `FIXES_gsPlayerVehicleTickCount`.

2017-08-18 17:47 UTC, ziggi commented on fixes.inc
> +	bool:FIXES_gsPlayerVehTrying[MAX_PLAYERS],
Same about booleans.

2017-08-18 17:47 UTC, ziggi commented on fixes.inc
> +			if (FIXES_gsVehicleIsLocked[vehicleid]) {
In fixes.inc we move the bracket on the next line.

2017-08-18 17:47 UTC, ziggi commented on fixes.inc
> + * AUTHOR:   rt-2 (https://github.com/Y-Less/)
Wrong url.

2017-08-18 17:47 UTC, ziggi commented on fixes.inc
> + * POST:     https://github.com/ziggi/samp-enterfix
Original post about this bug here: http://forum.sa-mp.com/showthread.php?t=560019

2017-08-18 17:47 UTC, ziggi commented on fixes.inc
> -#if FIXES_SilentKick && (FIX_OnVehicleMod || FIX_OnPlayerEnterVehicle || FIX_OnPlayerEnterVehicle_2)
What the point of this changes?

2017-08-18 18:07 UTC, IstuntmanI commented
That's exactly why I don't make pull requests that are too big ! XD

2017-08-18 18:18 UTC, IstuntmanI commented on fixes.inc
> + * POST:     https://github.com/ziggi/samp-enterfix
Confirmed: rt-2 is Y-Less undercover.

2017-08-18 21:23 UTC, rt-2 commented on fixes.inc
> + * AUTHOR:   rt-2 (https://github.com/Y-Less/)
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/971ae18732dedfa888b40df0596e079bf731605c

2017-08-18 21:24 UTC, rt-2 commented on fixes.inc
> + * POST:     https://github.com/ziggi/samp-enterfix
I wish I was Y_Less, the equivalent of Jesus to the SAMP Forum.
Anyhow I have still been uncovered: I copy my stuff from Y_Less works haha.

2017-08-18 21:25 UTC, rt-2 commented on fixes.inc
> -#if FIXES_SilentKick && (FIX_OnVehicleMod || FIX_OnPlayerEnterVehicle || FIX_OnPlayerEnterVehicle_2)
This must be a mistake, because I didn't removed the closing of the if anyway

2017-08-18 21:28 UTC, rt-2 commented on fixes.inc
> -#if FIXES_SilentKick && (FIX_OnVehicleMod || FIX_OnPlayerEnterVehicle || FIX_OnPlayerEnterVehicle_2)
Now I see better, this have no effect at all so I replaced it to its original position.
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/9c113e0d4dec89173612e3ce353a7f239f01c6b6

2017-08-18 21:35 UTC, rt-2 commented on fixes.inc
> + * POST:     https://github.com/ziggi/samp-enterfix
Should I add the forum post or replace by the forum post?

2017-08-18 23:16 UTC, rt-2 commented on fixes.inc
> +		player_data[playerid][e_IsOpening] = false;
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/3a5cf9bc8d61f0c38c53e9ae67936fe686832d48

2017-08-18 23:18 UTC, rt-2 commented on fixes.inc
> +	stock FIXES_GetVehicleParamsEx(vehicleid, engine, lights, alarm, doors, bonnet, boot, objective)
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/5ce6d8ae3e6b74c47d74908d1ecefd47c8d13288

2017-08-18 23:21 UTC, rt-2 commented on fixes.inc
> +		return GetVehicleParamsEx(vehicleid, engine, lights, alarm, doors, bonnet, boot, objective);
Yes totally, thank you that didn't work.
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/8e91421fb316098e8ca262412ec54b4cb9c49d0c

2017-08-18 23:23 UTC, rt-2 commented on fixes.inc
> +		#if !defined FILTERSCRIPT
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/ebf57a9e5d1187e02a51bd3cef42b17245111925

2017-08-18 23:24 UTC, rt-2 commented on fixes.inc
> +	static stock FIXES_StopPlayerEnterVehicle(playerid)
Damn and I saw that when I was going through the file and forgot it then!
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/4cdd88d0132a87f3cc6f99fbae52f5df73ae5b88

2017-08-18 23:27 UTC, rt-2 commented on fixes.inc
> +			if (FIXES_gsVehicleIsLocked[vehicleid]) {
Yeah sorry I do that too in my project, I think it's more visible.
I copied this line from a sloppy programmer https://github.com/ziggi/samp-enterfix/blob/master/enterfix.inc#L34 sorry!
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/e12925e4f15cfd10bf2081e1cd605584dae09157

2017-08-18 23:28 UTC, rt-2 commented on fixes.inc
> +	FIXES_gsPlayerVehID[MAX_PLAYERS],
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/13ddbf630b6660106602b30c8fa980d33dcda878

2017-08-18 23:28 UTC, rt-2 commented on fixes.inc
> +	FIXES_gsPlayerVehTickCount[MAX_PLAYERS],
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/13ddbf630b6660106602b30c8fa980d33dcda878

2017-08-18 23:36 UTC, rt-2 commented on fixes.inc
> +	bool:FIXES_gsPlayerVehEntering[MAX_PLAYERS],
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/e313629d2a3808463ba7ab903dadc182e831d41c

2017-08-18 23:36 UTC, rt-2 commented on fixes.inc
> +	bool:FIXES_gsPlayerVehTrying[MAX_PLAYERS],
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/e313629d2a3808463ba7ab903dadc182e831d41c

2017-08-18 23:40 UTC, rt-2 commented on fixes.inc
> + * POST:     https://github.com/ziggi/samp-enterfix
I decided to keep only the forum post. No where else there was a github link as the original post, and the repo link is in ziggi's profile which is credited, and all other fixes had only one 'post'.
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/c7a127cc66ca7fd9065c86092ebdf31cad02192c

2017-08-18 23:40 UTC, rt-2 commented
Well that should do it, let me know if you have anything else?
Thank you,
rt-2

2017-08-18 23:53 UTC, rt-2 reviewed
First time doing this, am I at the right spot?

2017-08-19 04:45 UTC, ziggi requested changes
Almost fine.

2017-08-19 04:45 UTC, ziggi commented on fixes.inc
> +			if (FIXES_gsPlayerBools[playerid] & e_FIXES_BOOLS_VEH_ENTER) {
Same about brackets :).

2017-08-19 04:45 UTC, ziggi commented on fixes.inc
> +		new vehicleid = FIXES_gsPlayerVehicleID[playerid],
Move to the next line:
```Pawn
new
	vehicleid = FIXES_gsPlayerVehicleID[playerid],
	engine, lights, alarm, doors, bonnet, boot, objective;
```

2017-08-19 04:45 UTC, ziggi commented on fixes.inc
> +
Extra line.

2017-08-19 04:45 UTC, ziggi commented on fixes.inc
> +	public FIXES_GetVehicleDoorsEx(vehicleid)
This should be also with _ prefix. And add one line between.
```Pawn
	forward _FIXES_GetVehicleDoorsEx(vehicleid);

 	public _FIXES_GetVehicleDoorsEx(vehicleid)
```

2017-08-19 04:45 UTC, ziggi commented on README.md
> +OnPlayerEnterVehicle_3 | No player animation when trying to enter the driver door of a locked vehicle. | [ziggi](https://github.com/ziggi)/[rt-2](https://github.com/rt-2) | [Link](https://github.com/
Old post url, should be: http://forum.sa-mp.com/showthread.php?t=560019

2017-08-19 04:47 UTC, ziggi commented on fixes.inc
> + * POST:     https://github.com/ziggi/samp-enterfix
Yes, of course.

2017-08-19 04:48 UTC, ziggi commented on fixes.inc
> +			if (FIXES_gsVehicleIsLocked[vehicleid]) {
I prefer this code style, but fixes.inc have different style.

2017-08-19 08:54 UTC, rt-2 commented on fixes.inc
> +	public FIXES_GetVehicleDoorsEx(vehicleid)
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/a9859fd79ed82114192afb22510bda4dc497d43d

2017-08-19 08:56 UTC, rt-2 commented on fixes.inc
> +		new vehicleid = FIXES_gsPlayerVehicleID[playerid],
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/ebd54742738cce835c6c9f47dd63fad01263cd96

2017-08-19 08:57 UTC, rt-2 commented on fixes.inc
> +
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/018e84deae22734592d70ff4b19cf12485fa3d45

2017-08-19 08:59 UTC, rt-2 commented on fixes.inc
> +			if (FIXES_gsPlayerBools[playerid] & e_FIXES_BOOLS_VEH_ENTER) {
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/b3ab260be1cf5989508d6c6a4ca6e3ed9fc8a33c and https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/30cb65981ed54208a3474a50c8646b5e4158816d

2017-08-19 09:00 UTC, rt-2 reviewed
Thank you

2017-08-19 09:01 UTC, rt-2 commented on README.md
> +OnPlayerEnterVehicle_3 | No player animation when trying to enter the driver door of a locked vehicle. | [ziggi](https://github.com/ziggi)/[rt-2](https://github.com/rt-2) | [Link](https://github.com/
https://github.com/Open-GTO/sa-mp-fixes/pull/64/commits/cb41de179daa0e209d72f50d68d08543bc61c3b6

2017-08-19 09:21 UTC, Y-Less commented
Honestly, I'm not even bothered about things like how many blank lines there are between `forward` and `public`, or if certain functions start with `_`.  I generally use that prefix when I can't make functions `static` (so publics), but need to indicate that they are internal and shouldn't really be called by users.  That's the only reason it is that way.

In fact, often I wouldn't even complain about brace position in a code review.  Consistency is nice, but they should be mosty used for actual logical problems IMHO.  Unless of course the code is truly ugly.

2017-08-19 09:23 UTC, Y-Less commented
One thing I will comment on though:

`(` - that is a bracket.

`{` - that is a brace.

They are different in both use and name.  For completion:

`<` - angle bracket.

`[` - square bracket.

2017-08-19 09:27 UTC, rt-2 commented
I think it's nice to have uniformity in the code it's easier to read after. Especially in this case where a lot  of people working on the same file.

2017-08-19 10:01 UTC, merged